### ISSUE TITLE
autoinstaller for heroku fails on missing sql table "wp_options"

### ISSUE THREAD

**Issue by rowntreerob** [technomile/Heroku-WordPress#15]
log errors: 

> 2022-01-12T15:09:17.302787+00:00 heroku[router]: at=info method=GET path="/" host=w-p-test.herokuapp.com request_id=b7557878-a05e-47d1-84f6-36d6433ef077 fwd="136.25.106.17" dyno=web.1 connect=0ms service=36ms status=500 bytes=169 protocol=http
> 2022-01-12T15:09:17.302042+00:00 app[web.1]: [12-Jan-2022 15:09:17 UTC] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'heroku_e46a769ee4752e8.wp_options' doesn't exist in /app/wp-includes/wp-db.php:1931
> 2022-01-12T15:09:17.302191+00:00 app[web.1]: Stack trace:
> 2022-01-12T15:09:17.302327+00:00 app[web.1]: #0 /app/wp-includes/wp-db.php(1931): mysqli_query()
> 2022-01-12T15:09:17.302491+00:00 app[web.1]: #1 /app/wp-includes/wp-db.php(1820): wpdb->_do_query()
> 2022-01-12T15:09:17.302626+00:00 app[web.1]: #2 /app/wp-includes/wp-db.php(2495): wpdb->query()
> 2022-01-12T15:09:17.302767+00:00 app[web.1]: #3 /app/wp-includes/option.php(197): wpdb->get_results()
> 2022-01-12T15:09:17.302920+00:00 app[web.1]: #4 /app/wp-includes/functions.php(1369): wp_load_alloptions()
> 2022-01-12T15:09:17.303121+00:00 app[web.1]: #5 /app/wp-includes/load.php(540): is_blog_installed()
> 2022-01-12T15:09:17.303832+00:00 app[web.1]: #6 /app/wp-settings.php(140): wp_not_installed()
> 2022-01-12T15:09:17.304034+00:00 app[web.1]: #7 /app/wp-config.php(106): require_once('...')
> 2022-01-12T15:09:17.304227+00:00 app[web.1]: #8 /app/wp-load.php(37): require_once('...')
> 2022-01-12T15:09:17.304358+00:00 app[web.1]: #9 /app/wp-blog-header.php(13): require_once('...')
> 2022-01-12T15:09:17.304462+00:00 app[web.1]: #10 /app/index.php(17): require('...')
> 2022-01-12T15:09:17.304497+00:00 app[web.1]: #11 {main}
> 2022-01-12T15:09:17.304644+00:00 app[web.1]:   thrown in /app/wp-includes/wp-db.php on line 1931
> 2022-01-12T15:09:17.304986+00:00 app[web.1]: 10.1.16.18 - - [12/Jan/2022:15:09:17 +0000] "GET / HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
> 2022-01-12T15:09:17.498001+00:00 app[web.1]: [Wed Jan 12 15:09:17.497093 2022] [core:error] [pid 155:tid 139982798817024] [client 10.1.28.211:33283] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'Lim
![Screenshot from 2022-01-12 07-15-56](https://user-images.githubusercontent.com/169984/149168102-703221de-0e02-4c25-a40d-63443b19c235.png)
![Screenshot from 2022-01-12 07-15-56](https://user-images.githubusercontent.com/169984/149168157-7e3fc60b-cbe4-44df-a714-fa043e30c553.png)
itInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://w-p-test.herokuapp.com/
> 2022-01-12T15:09:17.498378+00:00 app[web.1]: 10.1.28.211 - - [12/Jan/2022:15:09:17 +0000] "GET /favicon.ico HTTP/1.1" 500 528 "http://w-p-test.herokuapp.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
> 2022-01-12T15:09:17.497371+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=w-p-test.herokuapp.com request_id=b2971842-9b5b-4280-953c-df8cec184d6f fwd="136.25.106.17" dyno=web.1 connect=0ms service=5ms status=500 bytes=704 protocol=http

**Comment by rowntreerob** [comment]
logged on remote to heroku bash and on CLI ran wp-admin/admin.php ... getting same error there : 
![Screenshot from 2022-01-12 08-30-57](https://user-images.githubusercontent.com/169984/149181989-e70ab525-8aba-46f2-b22a-fd7382929d15.png)

**Comment by rowntreerob** [comment]
used CLI to connect to the remote , entered "use heroku_e46a769ee4752e8" 

  then "show tables"   which displays empty set .

  looks as tho a DB create is working but then the script to create the schema failed and there are no tables in that DB.
